//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentaacar
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch
    {
        public int branchNo { get; set; }
        public string branchName { get; set; }
        public Nullable<int> branchEmployee { get; set; }
        public Nullable<decimal> branchRevenue { get; set; }
        public Nullable<int> carSrock { get; set; }
    }
}
