//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentaacar
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        public int carNo { get; set; }
        public Nullable<decimal> carPrice { get; set; }
        public string carPlaque { get; set; }
        public string carModel { get; set; }
        public Nullable<System.DateTime> carYear { get; set; }
        public string carMotor { get; set; }
        public string carPacet { get; set; }
        public string carColor { get; set; }
        public Nullable<int> carTransmission { get; set; }
        public Nullable<int> branchNo { get; set; }
    }
}
