//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentaacar
{
    using System;
    using System.Collections.Generic;
    
    public partial class custumer
    {
        public int custumerID { get; set; }
        public string custumerName { get; set; }
        public string custumerPhone { get; set; }
        public Nullable<int> custumerAge { get; set; }
        public Nullable<decimal> custumerBalance { get; set; }
        public Nullable<decimal> custumerDeposit { get; set; }
        public Nullable<int> carNo { get; set; }
    }
}
