//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentaacar
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel
    {
        public int perNo { get; set; }
        public string perNameSurname { get; set; }
        public string perTel { get; set; }
        public string perTitle { get; set; }
        public string perMail { get; set; }
        public Nullable<decimal> perSalary { get; set; }
        public Nullable<int> branchNo { get; set; }
    }
}
